### ISSUE TITLE
Specify connection name to reuse connections

### ISSUE THREAD

**Issue by apgapg** [the-arijit-ray/azure-queue-wrapper#3]
Currently a new instance is made and existing one isnt reused when pushing message to queue.

We can specify connections name to reuse. This would also help in supporting multiple storage account.
Specifiying connection string everytime would unnecessary duplicate code

**Comment by the-arijit-ray** [comment]
Added in commit https://github.com/the-arijit-ray/azure-queue-wrapper/commit/7111a5758d4715c6909a8a9c6838a2d792e7a970
